language: ruby

rvm: 2.0.0

env:
  global:
  - SELENIUM_HOST=hub.browserstack.com
  - SELENIUM_PORT=80
  - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BS_AUTOMATE_BUILD="Travis build $TRAVIS_BUILD_NUMBER"
  - secure: "PcVAVdrUj1z7fztYklzExbkxCkwEgdKaaSt4eQNNuxdBvj8MwDAp7JvKasqAALBLJgcthj+jt+BU2l3LABPZyZPkl6A6FstoXvmK0fUAPr2k9InuiFX6UgybNKvhIQOyF++9bw0kCTZlkGn3KSw0vLZAx10/+XCb8mu7ghwylrI="
  - secure: "IO5ls6xcCpbgxEJFpKJhh5WT1FxwZOiwdhXs2OMElPCDAoMrQcooClvlSG6MWAY344F9p6jS3JFy0m8AZWw9IuJr5HeS36o5HS1Zf1+A/Awe8BDkyfHZTORZPU6VucFfLmZxgDXSFAmKxTaXUPhPQGXGbXuvT8KdkbqT43eA2HI="
  matrix:
  - SELENIUM_PLATFORM=WINDOWS SELENIUM_BROWSER=chrome SELENIUM_VERSION=27
  - BS_AUTOMATE_OS="OS X" BS_AUTOMATE_OS_VERSION=Lion SELENIUM_BROWSER=firefox SELENIUM_VERSION=24

before_script:
  - gem install selenium-webdriver
  - gem install cucumber
  - gem install parallel

script:
  - ruby google-search-generic.rb
  - cd cucumber; cucumber

